#!/usr/bin/env bash

set -e

SCRIPT_PATH="${BASH_SOURCE[*]}"
while [ -L "$SCRIPT_PATH" ]; do
  SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_PATH")" >/dev/null 2>&1 && pwd)"
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
  [[ $SCRIPT_PATH != /* ]] && SCRIPT_PATH="$SCRIPT_DIR/$SCRIPT_PATH"
done
SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_PATH")" >/dev/null 2>&1 && pwd)"
echo "$SCRIPT_DIR"

docker build \
  $(cat .env | sed 's/^/--build-arg /') \
  $(awk '{printf "-t %s ", $1}' "$SCRIPT_DIR/tags") \
  "$SCRIPT_DIR"
